# Generated by Django 5.1.6 on 2025-03-05 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoerSomUtgar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('begrunnelse', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Datoer som utgår',
                'verbose_name_plural': 'Datoer som utgår',
            },
        ),
        migrations.CreateModel(
            name='KontakterForening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('oppsummert', models.CharField(max_length=100)),
                ('detaljer', models.TextField()),
                ('dato', models.DateField(auto_now_add=True)),
                ('fulgt_opp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Forespørsler til forenigen',
                'verbose_name_plural': 'Forespørsler til forenigen',
            },
        ),
        migrations.CreateModel(
            name='MalgruppeAktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alder_eller_klasse', models.CharField(max_length=20, verbose_name='Alder/Kl')),
                ('vanskelighetsgrad_eller_formål', models.CharField(max_length=20, verbose_name='Vanskelighetsgrad/Formål')),
            ],
            options={
                'verbose_name': 'Målgruppe for aktivitet',
                'verbose_name_plural': 'Målgruppe for aktivitet',
            },
        ),
        migrations.CreateModel(
            name='MeldtInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('oppsummert', models.CharField(max_length=100)),
                ('detaljer', models.TextField()),
                ('dato', models.DateField(auto_now_add=True)),
                ('fulgt_opp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Meldt interesse for aktivitet',
                'verbose_name_plural': 'Meldt interesse for aktivitet',
            },
        ),
        migrations.CreateModel(
            name='Personell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100)),
                ('etternavn', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('person_nummer', models.CharField(max_length=11)),
                ('konto_nummer', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('adresse', models.CharField(max_length=100)),
                ('post_nummer', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('skatt_info', models.TextField(verbose_name='Hva trenger vi å vite om dine skatteforhold for å betale ut lønn?')),
                ('annen_info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Personell',
                'verbose_name_plural': 'Personell',
            },
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(max_length=20)),
                ('lonn', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Roller',
            },
        ),
        migrations.CreateModel(
            name='StedAktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omrade', models.CharField(max_length=40)),
                ('oppmote_sted', models.TextField()),
                ('samarbeids_partnere', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Sted for aktivitet',
                'verbose_name_plural': 'Sted for aktivitet',
            },
        ),
        migrations.CreateModel(
            name='TypeAktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aktivitet', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Type aktivitet',
                'verbose_name_plural': 'Type aktivtet',
            },
        ),
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppstart', models.DateField()),
                ('slutt', models.DateField()),
                ('kl_start', models.TimeField()),
                ('kl_slutt', models.TimeField()),
                ('antall_ganger', models.PositiveIntegerField()),
                ('pris', models.PositiveIntegerField()),
                ('datoer_som_utgar', models.ManyToManyField(to='hjemmeside.datoersomutgar')),
                ('malgruppe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.malgruppeaktivitet')),
            ],
            options={
                'verbose_name': 'Aktivitet',
                'verbose_name_plural': 'Aktiviteter',
            },
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=30)),
                ('etternavn', models.CharField(max_length=30)),
                ('alder', models.PositiveIntegerField()),
                ('fodt_ar', models.PositiveIntegerField()),
                ('adresse', models.CharField(max_length=100)),
                ('post_nummer', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('foto_tillatelse', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nei')])),
                ('hoved_kontakt_tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('hoved_kontakt_mail', models.EmailField(max_length=100)),
                ('hoved_kontakt_rolle', models.CharField(choices=[('Deltager/medlem', 'Deltager/medlem'), ('Far', 'Far'), ('Mor', 'Mor'), ('Verge', 'Verge'), ('Annen Familie', 'Annen Familie')], max_length=20)),
                ('kontakt2_tlf', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('kontakt2_mail', models.EmailField(blank=True, max_length=100)),
                ('kontakt2_rolle', models.CharField(blank=True, choices=[('Deltager/medlem', 'Deltager/medlem'), ('Far', 'Far'), ('Mor', 'Mor'), ('Verge', 'Verge'), ('Annen Familie', 'Annen Familie')], max_length=20)),
                ('kontakt3_tlf', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('kontakt3_mail', models.EmailField(blank=True, max_length=100)),
                ('kontakt3_rolle', models.CharField(blank=True, choices=[('Deltager/medlem', 'Deltager/medlem'), ('Far', 'Far'), ('Mor', 'Mor'), ('Verge', 'Verge'), ('Annen Familie', 'Annen Familie')], max_length=20)),
                ('annet', models.TextField(blank=True)),
                ('notater', models.TextField(blank=True)),
                ('pameldt', models.ManyToManyField(blank=True, to='hjemmeside.aktivitet')),
            ],
            options={
                'verbose_name': 'Medlem',
                'verbose_name_plural': 'Medlemmer',
            },
        ),
        migrations.CreateModel(
            name='AktivitetPersonell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hjemmeside.aktivitet')),
                ('personell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hjemmeside.personell')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.rolle')),
            ],
            options={
                'verbose_name': 'Hvem/Hvor/Hvilken Rolle',
                'verbose_name_plural': 'Hvem/Hvor/Hvilken Rolle',
            },
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='ansvars_personer',
            field=models.ManyToManyField(through='hjemmeside.AktivitetPersonell', to='hjemmeside.personell'),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='sted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.stedaktivitet'),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='type_aktivitet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.typeaktivitet'),
        ),
        migrations.CreateModel(
            name='KontaktListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.aktivitet')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlem')),
            ],
            options={
                'verbose_name': 'Kontakt lister',
                'verbose_name_plural': 'Kontakt lister',
                'unique_together': {('aktivitet', 'medlem')},
            },
        ),
        migrations.CreateModel(
            name='Oppmote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilstede_1', models.BooleanField(default=False)),
                ('tilstede2', models.BooleanField(default=False)),
                ('tilstede3', models.BooleanField(default=False)),
                ('tilstede4', models.BooleanField(default=False)),
                ('tilstede5', models.BooleanField(default=False)),
                ('tilstede6', models.BooleanField(default=False)),
                ('tilstede7', models.BooleanField(default=False)),
                ('tilstede8', models.BooleanField(default=False)),
                ('tilstede9', models.BooleanField(default=False)),
                ('tilstede10', models.BooleanField(default=False)),
                ('tilstede11', models.BooleanField(default=False)),
                ('tilstede12', models.BooleanField(default=False)),
                ('tilstede13', models.BooleanField(default=False)),
                ('tilstede14', models.BooleanField(default=False)),
                ('tilstede15', models.BooleanField(default=False)),
                ('tilstede16', models.BooleanField(default=False)),
                ('tilstede17', models.BooleanField(default=False)),
                ('tilstede18', models.BooleanField(default=False)),
                ('tilstede19', models.BooleanField(default=False)),
                ('tilstede20', models.BooleanField(default=False)),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.aktivitet')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlem')),
            ],
            options={
                'verbose_name': 'Oppmøte lister',
                'verbose_name_plural': 'Oppmøte lister',
                'unique_together': {('aktivitet', 'medlem')},
            },
        ),
        migrations.CreateModel(
            name='TimeListePersonell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato_gjennomført', models.DateField()),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.aktivitet')),
                ('personell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.personell')),
            ],
            options={
                'verbose_name': 'Timeliste for personell',
                'verbose_name_plural': 'Timeliste for personell',
                'unique_together': {('personell', 'aktivitet', 'dato_gjennomført')},
            },
        ),
    ]
