# Generated by Django 5.1.6 on 2025-04-20 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dato', models.DateField()),
                ('slutt_dato', models.DateField(blank=True, editable=False, null=True)),
                ('kl_start', models.TimeField()),
                ('kl_slutt', models.TimeField()),
                ('antall_ganger', models.PositiveIntegerField()),
                ('antall_plasser', models.PositiveIntegerField()),
                ('ledige_plasser', models.PositiveIntegerField()),
                ('pris_vanlig', models.PositiveIntegerField()),
                ('pris_drop_in', models.PositiveIntegerField()),
                ('dag_interval', models.PositiveIntegerField()),
                ('status_oppstart', models.CharField(choices=[('Kommende', 'Kommende'), ('Pågående', 'Pågående'), ('Avsluttet', 'Avsluttet')], default='Kommende', max_length=20)),
            ],
            options={
                'verbose_name': 'Aktivitet',
                'verbose_name_plural': 'Aktiviteter',
            },
        ),
        migrations.CreateModel(
            name='BetalingsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Betalingstype',
                'verbose_name_plural': 'Betalingstyper',
            },
        ),
        migrations.CreateModel(
            name='DatoerSomUtgar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('begrunnelse', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Datoer som utgår',
                'verbose_name_plural': 'Datoer som utgår',
            },
        ),
        migrations.CreateModel(
            name='ForesporsleKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=30)),
                ('beskrivelse', models.TextField()),
            ],
            options={
                'verbose_name': 'Forspørsel Kategori',
                'verbose_name_plural': 'Forespørsel Kategorier',
            },
        ),
        migrations.CreateModel(
            name='MalgruppeAktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alder_eller_klasse', models.CharField(max_length=20, verbose_name='Alder/Kl')),
                ('vanskelighetsgrad_eller_formal', models.CharField(max_length=20, verbose_name='Vanskelighetsgrad/Formål')),
            ],
            options={
                'verbose_name': 'Målgruppe for aktivitet',
                'verbose_name_plural': 'Målgruppe for aktivitet',
            },
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=30)),
                ('etternavn', models.CharField(max_length=30)),
                ('fodt_ar', models.DateField()),
                ('alder', models.PositiveIntegerField(editable=False)),
                ('adresse', models.CharField(max_length=100)),
                ('post_nummer', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('foto_tillatelse', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nei')])),
                ('hoved_kontakt_tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('hoved_kontakt_mail', models.EmailField(max_length=100)),
                ('hoved_kontakt_rolle', models.CharField(choices=[('Deltager/medlem', 'Deltager/medlem'), ('Far', 'Far'), ('Mor', 'Mor'), ('Verge', 'Verge'), ('Annen Familie', 'Annen Familie')], max_length=20)),
                ('kontakt2_tlf', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('kontakt2_mail', models.EmailField(blank=True, max_length=100)),
                ('kontakt2_rolle', models.CharField(blank=True, choices=[('Deltager/medlem', 'Deltager/medlem'), ('Far', 'Far'), ('Mor', 'Mor'), ('Verge', 'Verge'), ('Annen Familie', 'Annen Familie')], max_length=20)),
                ('kontakt3_tlf', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('kontakt3_mail', models.EmailField(blank=True, max_length=100)),
                ('kontakt3_rolle', models.CharField(blank=True, choices=[('Deltager/medlem', 'Deltager/medlem'), ('Far', 'Far'), ('Mor', 'Mor'), ('Verge', 'Verge'), ('Annen Familie', 'Annen Familie')], max_length=20)),
                ('annet', models.TextField(blank=True)),
                ('notater', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Medlem',
                'verbose_name_plural': 'Medlemmer',
            },
        ),
        migrations.CreateModel(
            name='Personell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100)),
                ('etternavn', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('fodsels_dato', models.CharField(blank=True, max_length=11)),
                ('konto_nummer', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('adresse', models.CharField(max_length=100)),
                ('post_nummer', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('skatt_info', models.TextField(verbose_name='Hva trenger vi å vite om dine skatteforhold for å betale ut lønn?')),
                ('annen_info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Personell',
                'verbose_name_plural': 'Personell',
            },
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(max_length=20)),
                ('standard_lonn', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Roller',
            },
        ),
        migrations.CreateModel(
            name='StedAktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omrade', models.CharField(max_length=40)),
                ('oppmote_sted', models.TextField()),
                ('samarbeids_partnere', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Sted for aktivitet',
                'verbose_name_plural': 'Sted for aktivitet',
            },
        ),
        migrations.CreateModel(
            name='TypeAktivitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aktivitet', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Type aktivitet',
                'verbose_name_plural': 'Type aktivtet',
            },
        ),
        migrations.CreateModel(
            name='AktivitetDatoer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aktivitet_datoer', to='hjemmeside.aktivitet')),
            ],
            options={
                'verbose_name': 'Aktivitets dato',
                'verbose_name_plural': 'Aktivitets datoer',
                'ordering': ['dato'],
                'unique_together': {('aktivitet', 'dato')},
            },
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='datoer_som_utgar',
            field=models.ManyToManyField(to='hjemmeside.datoersomutgar'),
        ),
        migrations.CreateModel(
            name='DeltagerOppmote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilstede', models.BooleanField(default=False)),
                ('aktivitet_datoer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.aktivitetdatoer')),
            ],
        ),
        migrations.CreateModel(
            name='BetalingStatusDropIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField()),
                ('original_pris', models.PositiveIntegerField()),
                ('rabatt', models.PositiveIntegerField(default=0, help_text='Prosentrabatt: skriv in et tall mellom 0 og 1. Eks. 0.70 = 70%.', validators=[django.core.validators.MaxValueValidator(1)])),
                ('endelig_pris', models.PositiveIntegerField()),
                ('status_betaling', models.BooleanField(default=False)),
                ('deltager_oppmote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.deltageroppmote')),
            ],
        ),
        migrations.CreateModel(
            name='KundeKontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('detaljer', models.TextField()),
                ('dato', models.DateField(auto_now_add=True)),
                ('fulgt_opp', models.BooleanField(default=False)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.foresporslekategori')),
            ],
            options={
                'verbose_name': 'Meldt interesse for aktivitet',
                'verbose_name_plural': 'Meldt interesse for aktivitet',
            },
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='malgruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.malgruppeaktivitet'),
        ),
        migrations.CreateModel(
            name='MedlemPameldt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_in', models.BooleanField(default=False)),
                ('aktivitet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pameldte_deltagere', to='hjemmeside.aktivitet')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlem')),
            ],
        ),
        migrations.AddField(
            model_name='deltageroppmote',
            name='medlem_pameldt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlempameldt'),
        ),
        migrations.CreateModel(
            name='BetalingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pris', models.PositiveIntegerField()),
                ('rabatt', models.PositiveIntegerField(default=0, help_text='Prosentrabatt: skriv in et tall mellom 0 og 1. Eks. 0.70 = 70%.', validators=[django.core.validators.MaxValueValidator(1)])),
                ('endelig_pris', models.PositiveIntegerField()),
                ('status_betaling', models.BooleanField(default=False)),
                ('type_betaling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.betalingstype')),
                ('medlem_pameldt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlempameldt')),
            ],
        ),
        migrations.CreateModel(
            name='PersonellRolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.personell')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.rolle')),
            ],
            options={
                'verbose_name': 'Personell i rollen som',
                'verbose_name_plural': 'Personell i rollen som',
            },
        ),
        migrations.CreateModel(
            name='PersonellOppmote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utbetalt_lonn', models.BooleanField(default=False)),
                ('aktivitet_datoer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.aktivitetdatoer')),
                ('personel_rolle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.personellrolle')),
            ],
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='personell_rolle',
            field=models.ManyToManyField(to='hjemmeside.personellrolle'),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='sted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.stedaktivitet'),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='type_aktivitet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.typeaktivitet'),
        ),
    ]
