# Generated by Django 5.1.6 on 2025-04-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeaktivitet',
            options={'verbose_name': 'Aktivitetsinfo/Type aktivitet', 'verbose_name_plural': 'Type aktivtet'},
        ),
    ]
