# Generated by Django 5.1.6 on 2025-04-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0002_alter_typeaktivitet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeaktivitet',
            options={'verbose_name': 'Type aktivitet', 'verbose_name_plural': 'Aktivitetsinfo/Type aktivtet'},
        ),
    ]
