# Generated by Django 5.1.6 on 2025-04-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0003_alter_typeaktivitet_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForesporsleKategori',
            new_name='ForesporselKategori',
        ),
        migrations.AlterModelOptions(
            name='aktivitetdatoer',
            options={'verbose_name': 'Datoer for aktivitet', 'verbose_name_plural': 'Aktivitetsinfo: Datoer for aktiviteten'},
        ),
        migrations.AlterModelOptions(
            name='betalingstatus',
            options={'verbose_name': 'Status betaling', 'verbose_name_plural': 'Medlemsinfo: Status Betaling'},
        ),
        migrations.AlterModelOptions(
            name='betalingstatusdropin',
            options={'verbose_name': 'Betaling status drop-in', 'verbose_name_plural': 'Medlemsinfo: Betaling status drop-in'},
        ),
        migrations.AlterModelOptions(
            name='betalingstype',
            options={'verbose_name': 'Betalingstype', 'verbose_name_plural': 'Medlemsinfo: Betalingstyper'},
        ),
        migrations.AlterModelOptions(
            name='datoersomutgar',
            options={'verbose_name': 'Datoer som utgår', 'verbose_name_plural': 'Aktivitetsinfo: Datoer som utgår'},
        ),
        migrations.AlterModelOptions(
            name='deltageroppmote',
            options={'verbose_name': 'Deltager oppmøte', 'verbose_name_plural': 'Medlemsinfo: Deltager oppmøte'},
        ),
        migrations.AlterModelOptions(
            name='foresporselkategori',
            options={'verbose_name': 'Kategori for forespørsler', 'verbose_name_plural': 'Forespørselinfo: Kategorier'},
        ),
        migrations.AlterModelOptions(
            name='kundekontakt',
            options={'verbose_name': 'Forspørsel', 'verbose_name_plural': 'Forspørsler'},
        ),
        migrations.AlterModelOptions(
            name='malgruppeaktivitet',
            options={'verbose_name': 'Målgruppe for aktivitet', 'verbose_name_plural': 'Aktivitetsinfo: Målgruppe for aktivitet'},
        ),
        migrations.AlterModelOptions(
            name='medlempameldt',
            options={'verbose_name': 'Påmeldt deltager', 'verbose_name_plural': 'Medlemsinfo: Deltager påmelding'},
        ),
        migrations.AlterModelOptions(
            name='personelloppmote',
            options={'verbose_name': 'Personell oppmøte', 'verbose_name_plural': 'Personellinfo: Personell oppmøte'},
        ),
        migrations.AlterModelOptions(
            name='personellrolle',
            options={'verbose_name': 'Personell i rollen som', 'verbose_name_plural': 'Personellinfo: Personell i rollen som'},
        ),
        migrations.AlterModelOptions(
            name='rolle',
            options={'verbose_name': 'Rolle', 'verbose_name_plural': 'Personellinfo: Roller'},
        ),
        migrations.AlterModelOptions(
            name='stedaktivitet',
            options={'verbose_name': 'Sted for aktivitet', 'verbose_name_plural': 'Aktivitetsinfo: Sted for aktivitet'},
        ),
        migrations.AlterModelOptions(
            name='typeaktivitet',
            options={'verbose_name': 'Type aktivitet', 'verbose_name_plural': 'Aktivitetsinfo: Type aktivtet'},
        ),
        migrations.AlterUniqueTogether(
            name='aktivitetdatoer',
            unique_together=set(),
        ),
    ]
