# Generated by Django 5.2.3 on 2025-06-12 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0004_rename_foresporslekategori_foresporselkategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilde', models.ImageField(upload_to='bilder/')),
                ('alternativ_tekst', models.CharField(max_length=100)),
                ('rekkefolge', models.IntegerField()),
                ('i_bruk', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bilde',
                'verbose_name_plural': 'Bilder',
                'ordering': ['rekkefolge'],
            },
        ),
        migrations.CreateModel(
            name='ForeningInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisasjon_navn', models.CharField(default='Bergen Parkour', max_length=40)),
                ('adresse', models.CharField(max_length=100)),
                ('post_nummer', models.CharField(max_length=40)),
                ('organisasjon_nummer', models.CharField(default='923132228', max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('kontakt_tlf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')])),
                ('kontakt_mail', models.CharField(default='bergen.parkour@gmail.com', max_length=40)),
                ('facebook_side', models.CharField(default='Bergenparkour', max_length=20)),
                ('instagram_side', models.CharField(default='bergenparkour', max_length=20)),
                ('om_foreningen', models.TextField()),
            ],
            options={
                'verbose_name': 'Informasjon om foreningen',
                'verbose_name_plural': 'Informasjon om foreningen',
            },
        ),
        migrations.CreateModel(
            name='GenerellKursInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informasjon', models.JSONField()),
                ('i_bruk', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Informasjon om kursene',
                'verbose_name_plural': 'Informasjon om kursene',
            },
        ),
        migrations.AlterModelOptions(
            name='betalingstatus',
            options={'verbose_name': 'Betaling status', 'verbose_name_plural': 'Medlemsinfo: Betaling status'},
        ),
        migrations.AlterModelOptions(
            name='datoersomutgar',
            options={'ordering': ['dato'], 'verbose_name': 'Datoer som utgår', 'verbose_name_plural': 'Aktivitetsinfo: Datoer som utgår'},
        ),
        migrations.AlterField(
            model_name='datoersomutgar',
            name='dato',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='stedaktivitet',
            name='samarbeids_partnere',
            field=models.JSONField(blank=True, default=list, help_text='\n        Må formateres som JSON. Anbefalt format [{"Info1": "Noe om de", "Kontaktinfo1": "Person: tlf"} , {"Info2": "Noe", "K2": "P:t"}]\n        '),
        ),
    ]
