# Generated by Django 5.2.3 on 2025-06-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0005_bilde_foreninginfo_generellkursinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreninginfo',
            name='i_bruk',
            field=models.BooleanField(default=False),
        ),
    ]
