# Generated by Django 5.2.3 on 2025-07-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0006_foreninginfo_i_bruk'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundekontakt',
            name='navn',
            field=models.CharField(default='Morten', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kundekontakt',
            name='fulgt_opp',
            field=models.CharField(choices=[('Motatt', 'Motatt'), ('Pågående', 'Pågående'), ('Ferdig', 'Ferdig')], max_length=10),
        ),
    ]
