# Generated by Django 5.2.3 on 2025-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0007_kundekontakt_navn_alter_kundekontakt_fulgt_opp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundekontakt',
            name='fulgt_opp',
            field=models.CharField(choices=[('Motatt', 'Motatt'), ('Pågående', 'Pågående'), ('Ferdig', 'Ferdig')], default='Motatt', max_length=10),
        ),
    ]
