# Generated by Django 5.2.3 on 2025-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0008_alter_kundekontakt_fulgt_opp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitet',
            name='merknader',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bilde',
            name='bilde',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
