# Generated by Django 5.2.3 on 2025-10-05 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjemmeside', '0009_aktivitet_merknader_alter_bilde_bilde'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropInBetaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KunMedlemmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='deltageroppmote',
            name='aktivitet_datoer',
        ),
        migrations.RemoveField(
            model_name='personelloppmote',
            name='aktivitet_datoer',
        ),
        migrations.RemoveField(
            model_name='betalingstatus',
            name='medlem_pameldt',
        ),
        migrations.RemoveField(
            model_name='betalingstatus',
            name='type_betaling',
        ),
        migrations.RemoveField(
            model_name='betalingstatusdropin',
            name='deltager_oppmote',
        ),
        migrations.RemoveField(
            model_name='deltageroppmote',
            name='medlem_pameldt',
        ),
        migrations.RemoveField(
            model_name='personelloppmote',
            name='personel_rolle',
        ),
        migrations.AlterModelOptions(
            name='medlempameldt',
            options={},
        ),
        migrations.RemoveField(
            model_name='aktivitet',
            name='dag_interval',
        ),
        migrations.RemoveField(
            model_name='aktivitet',
            name='ledige_plasser',
        ),
        migrations.RemoveField(
            model_name='aktivitet',
            name='status_oppstart',
        ),
        migrations.RemoveField(
            model_name='medlempameldt',
            name='drop_in',
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='datoer',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='en_gang_i_uken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aktivitet',
            name='generell_info',
            field=models.ManyToManyField(to='hjemmeside.generellkursinfo'),
        ),
        migrations.AddField(
            model_name='generellkursinfo',
            name='beskrivelse',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medlempameldt',
            name='dato_pameldt',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medlempameldt',
            name='oppfolging_notater',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medlempameldt',
            name='status_pamelding',
            field=models.CharField(choices=[('pameldt', 'Pameldt'), ('avmeldt', 'Avmeldt'), ('venteliste', 'Venteliste')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medlempameldt',
            name='trenger_oppfolging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medlempameldt',
            name='type_betaling',
            field=models.CharField(choices=[('drop_in', 'Drop-In'), ('vanlig', 'Vanlig'), ('aktivitetskortet', 'Aktivitetskortet'), ('gratis', 'Gratis'), ('friplass', 'Friplass'), ('redusert betaling', 'Redusert Betaling')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='antall_ganger',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitet',
            name='slutt_dato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilde',
            name='bilde',
            field=models.ImageField(help_text='Må ha en ratio på 16:9 (for eksempel 1920x1080 eller 1280x720)', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='generellkursinfo',
            name='informasjon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='alder',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medlempameldt',
            name='aktivitet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.aktivitet'),
        ),
        migrations.AlterField(
            model_name='personell',
            name='fodsels_dato',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d+$', 'Kun tillatt med tall. Fjern tomrom.')]),
        ),
        migrations.AlterField(
            model_name='personell',
            name='skatt_info',
            field=models.TextField(verbose_name='Hva trenger vi å vite om dine skatteforhold for å betale ut lønn? Type informasjon om skattekort/frikort.'),
        ),
        migrations.CreateModel(
            name='AktivitetskortetDeltager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivitetskort_bilde1', models.ImageField(blank=True, null=True, upload_to='aktivitetskort/')),
                ('aktivitetskort_bilde2', models.ImageField(blank=True, null=True, upload_to='aktivitetskort/')),
                ('aktivitetskort_godkjent', models.BooleanField(default=False)),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlem')),
            ],
        ),
        migrations.CreateModel(
            name='BetalingRegistrering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belop', models.PositiveIntegerField()),
                ('dato', models.DateTimeField(blank=True, null=True)),
                ('betaling_status', models.CharField(choices=[('venter', 'Venter på betaling'), ('godkjent', 'Godkjent'), ('feilet', 'Feilet'), ('refundert', 'Refundert'), ('kansellert', 'Kansellert')], default='venter', max_length=20)),
                ('kvittering_url', models.URLField(blank=True)),
                ('transaksjons_id', models.CharField(blank=True, max_length=100)),
                ('betaling_formal', models.JSONField(default=list)),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.medlem')),
            ],
            options={
                'verbose_name': 'Betaling fra medlem',
                'verbose_name_plural': 'Betalinger fra medlemmer',
            },
        ),
        migrations.AddField(
            model_name='medlempameldt',
            name='betaling_registrert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hjemmeside.betalingregistrering'),
        ),
        migrations.DeleteModel(
            name='AktivitetDatoer',
        ),
        migrations.DeleteModel(
            name='BetalingStatus',
        ),
        migrations.DeleteModel(
            name='BetalingsType',
        ),
        migrations.DeleteModel(
            name='BetalingStatusDropIn',
        ),
        migrations.DeleteModel(
            name='DeltagerOppmote',
        ),
        migrations.DeleteModel(
            name='PersonellOppmote',
        ),
    ]
